# -*- coding: utf-8 -*-

import unittest
from testcase.test_albumplay import test_albumplay_case
from testcase.test_start import testcase
from testcase.test_radiopage import test_radiopage_case
from HTMLTestRunner_Chart import HTMLTestRunner
import time

'''单独执行某些Case'''
# suite = unittest.TestSuite()
# testcase1 = [test_albumplay_case("test11_moredown")]
# suite.addTests(testcase1)

# '''单独执行某些Case'''
# suite = unittest.TestSuite()
# testcase1 = [testcase("test_01login")]
# suite.addTests(testcase1)

'''执行指定模块下的所有Case'''
# suite=unittest.TestSuite()
# suite.addTests(unittest.TestLoader().loadTestsFromTestCase(testcase))
# suite.addTests(unittest.TestLoader().loadTestsFromTestCase(test_radiopage_case))


# '''执行目录下的所有case'''
path='./testcase/'
suite=unittest.defaultTestLoader.discover(path,pattern="test_*.py")

'''生成测试报告'''
if __name__=="__main__":
    now = time.strftime("%Y-%m-%d %H_%M_%S")
    filename = './report/' + now + '_result.html'
    with open(filename, 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title=u'云听 android Test Report',
                                description='generated by HTMLTestRunner.',
                                retry=3,
                                verbosity=2,
                                save_last_try=False
                                )
        run=HTMLTestRunner()
        runner.run(suite)

